name: Version

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          NOW=$(date +"%Y-%m-%d-%H%M")
          git tag "v${NOW}"
          git push origin "v${NOW}"
