name: Version

on:
  workflow_dispatch:
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          NOW=$(date +"%Y-%m-%d-%H%M")
          git tag "v${NOW}"
