name: Docker Image CI

on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  schedule:
    - cron: '0 0 */14 * *' # Runs every 2 weeks
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get the version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            echo ::set-output name=VERSION::v$(date +"%Y-%m-%d-%H%M")
          else
            echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
          fi
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: chrismckee/rancher-cli-forbuild:${{ steps.get_version.outputs.VERSION }},chrismckee/rancher-cli-forbuild:latest
